var form                    = $("#save-organisation-validate");
var save_btn                = $("#save_btn");
var alert_modal             = $("#alert_modal");
var organisation_type_id    = $('select[id^="organisation_type_id"]');
var organisation_id         = $('select[id^="organisation_id"]');
var name                    = $("#name");
var registration_number     = $("#registration_number");
var email                   = $("#email");
var phone                   = $("#phone");